### ISSUE TITLE
Driver does not support FP-25 air quality monitors

### ISSUE THREAD

**Issue by hairem** [numat/alicat#30]
All I am trying to do is get a reading:
from cal import Old_tables
from alicat import FlowMeter

flow = FlowMeter(port="/dev/ttyUSB0")
value = flow.get()
print(str(value))
 and I get the error message:
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    value = flow.get()
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 127, in get
    for k, v in zip(self.keys, values)}
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 127, in <dictcomp>
    for k, v in zip(self.keys, values)}
ValueError: could not convert string to float: '2022-12-01'

**Comment by alexrudd2** [comment]
Can you add a `print(values)` to line 113?
```python
        command = '{addr}\r'.format(addr=self.address)
        line = self._write_and_read(command, retries)
        spl = line.split()
        address, values = spl[0], spl[1:]
      ++print(values)
```

It looks like this flowmeter may be returning a date, which I haven't seen before.  unfortunately, I don't have one at hand to test.

**Comment by alexrudd2** [comment]
Also, what's the serial number?  Alicat tech support can tell you exactly what that model will output over serial.  Sometimes @marinapalese lurks in this repo, also.

**Comment by hairem** [comment]
Sn: 278608
It's a FP-25BT

**Comment by hairem** [comment]
it doesn't support just reading the outputs? isn't it a mass flow meter?

**Comment by alexrudd2** [comment]
OK, that's interesting.  Didn't even know this device existed!  This repository does not support anything other than the M- and MC-series differential pressure flow meters/controllers.  I would merge a PR extending to other devices, but cannot provide support for other devices we don't have.

The manual is provided here: https://documents.alicat.com/manuals/Alicat_FP-25_Calibrator_Manual.pdf

Page 42 lists the serial communications format.
![Screenshot 2022-12-05 at 11 25 21 AM](https://user-images.githubusercontent.com/52292902/205702363-03cc7160-1285-48ed-b848-63ba13c5affc.png)

Note the date/time at the front of the data frame, and pressure source/humidity at the end.  Those are what's confusing the existing driver, which does not know about them.

**Comment by hairem** [comment]
I have been using the serial lines directly before using this library but the putout shifts with time. Thank you for the help.

**Comment by alexrudd2** [comment]
I'm sorry I can't help directly.  I think you have a couple of options.
(1) Fork this repository and extend the functionality yourself, using the manual above.
(2) Contact Alicat support - @marinapalese / marina.palese@alicat.com would be my first contact
(3) Contact @JosephHickey1 (JosephRHickey@Outlook.com) and ask him about his [repository Alicat-Python](https://github.com/JosephHickey1/Alicat-Python).  I know very little about it but believe the intention was to make a more generalized controller.  I do not know his current relationship with Alicat - he used to be employed there but no longer.  Perhaps he is available as a contract programmer?
(4) Look through the manual and see if there is a way of disabling the "extra" data on the device to avoid confusing the driver as-is.  (I see this as unlikely)

I'm happy to review / merge any code generated by the above strategies.  Good luck :)

**Comment by hairem** [comment]
I will probably just make my own library for the project I am working on, was just trying to use what was already available. Or maybe I will do as you suggest and branch this library for my project, it is an in-house script so I have no plans to sell or distribute it.

**Comment by hairem** [comment]
After adding the print line I get this now:
['0000000', '2022-12-05', '0010:46:41', '+0755.3', '+0000.5', '+754.86', '+018.72', 'P', '+00.001', '+00.001', '049', 'RHAir']
Traceback (most recent call last):
  File "/home/pi/.local/bin/alicat", line 10, in <module>
    sys.exit(run())
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/__init__.py", line 48, in run
    command_line(args)
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 567, in command_line
    state = flow_controller.get()
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 390, in get
    state = FlowMeter.get(self, retries)
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 128, in get
    for k, v in zip(self.keys, values)}
  File "/home/pi/.local/lib/python3.7/site-packages/alicat/serial.py", line 128, in <dictcomp>
    for k, v in zip(self.keys, values)}
ValueError: could not convert string to float: '2022-12-05'

the string is output but so is the error about it not being formated right
PROGRESS!!

**Comment by alexrudd2** [comment]
> As for the device, we just ordered these maybe 2 years ago, and are the standard we have in the office. I'm surprised you are unaware of them. Are these some kind of special meters?

I don't work for Alicat, we just buy (some of) their equipment.  We use another vendor for humidity logging.

**Comment by hairem** [comment]
Oh, my bad. They linked to you so I thought you worked for them.

**Comment by hairem** [comment]
I got it to work, somewhat, but commenting out the lines 114-127.
now I get "['0000000', '2022-12-05', '0011:32:10', '+0755.1', '+0000.4', '+754.73', '+019.20', 'P', '+00.000', '+00.000', '049', 'RHAir']
None
"

**Comment by JosephHickey1** [comment]
Pushing a stable version of the Alicat-Python was actually my last hurrah with Alicat but I'm still around and happy to support the library as I can. Bill Nick at Alicat is currently the caretaker for the program though in case issues like this pop up on the future. 

As Alex has said, updating the self.keys list to include the time and date information should resolve this. Alternatively, the other library should dynamically retrieve the keys when the program does initialization for the first time for the device.

**Comment by hairem** [comment]
Again, thank you for all your help.
